name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up dependencies
      run: sudo bash -c "apt update && apt install libgtk-3-dev -y"
    - name: Build
      run: cargo build --release
